[id="REX_pull_based_provider_{context}"]
= REX pull based provider 

Remote Execution has been around for a while now and has served SSH-based execution very well.
 
Now, {Project} has a ‘pull’ based provider that has the features of REX but with a deployment model similar to katello-agent. 

This provider uses MQTT as its messaging protocol and includes an MQTT client running on each content host.

In order to tune the MQTT server (`mosquitto`) and increase the number of clients (content hosts) connnected to it, you can follow the following procedure on the {Project} server:

.Procedure
. Enable the feature using: `{foreman-installer} --foreman-proxy-plugin-remote-execution-script-mode pull-mqtt` (this will change the REX transport mode from the default SSH one to MQTT).
  It's important to mention that one {Project} server ({ProjectServer} or {SmartProxyServer}) can only use one transport mode: SSH or MQTT.

. To increase the default number of clients accepted by the MQTT server, create the following system unit definition file and set its contents as specified in the below given example (this will allow the `mosquitto` service to handle ~5000 clients):
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
cat >/etc/systemd/system/mosquitto.service.d/limits.conf <<__EOF__
[Service]
LimitNOFILE=5000
__EOF__
----
. Once the file has been edited, the following commands need to be run to make the tuning come into effect:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
systemctl daemon-reload
systemctl restart mosquitto.service
----
